version: "3"
services:
    web:
        build: .
        container_name: docker-php
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - default
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7.29
        container_name: docker-mysql
        environment:
            #MYSQL_DATABASE: database_name
            #MYSQL_USER: my_username
            #MYSQL_PASSWORD: my_password
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        restart: always
        volumes: 
            - /home/ryzen-fedora/Software/Docker-Volumes/mysql:/var/lib/mysql
        networks:
            - default        