-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 00:08:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Alesi_BD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Alesi_BD` ;

-- -----------------------------------------------------
-- Schema Alesi_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alesi_BD` DEFAULT CHARACTER SET utf8 ;
USE `Alesi_BD` ;

-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tusuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tusuarios` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tusuarios` (
  `Usuario` VARCHAR(45) NOT NULL,
  `id_persona` INT NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `F_alta` DATE NOT NULL,
  `F_ultima_conexion` DATE NULL,
  PRIMARY KEY (`Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tpersonas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tpersonas` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tpersonas` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `ApellidoP` VARCHAR(50) NOT NULL,
  `ApellidoM` VARCHAR(50) NOT NULL,
  `Edad` INT NULL,
  `Sexo` VARCHAR(1) NULL,
  `Telefono` VARCHAR(20) NULL,
  `Email` VARCHAR(45) NULL,
  `id_Empresa` VARCHAR(45) NULL,
  `Cargo` VARCHAR(90) NULL,
  `Otros` VARCHAR(45) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tcaso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tcaso` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tcaso` (
  `id_caso` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  `Tipo_caso` VARCHAR(45) NOT NULL,
  `F_alta` DATE NOT NULL,
  `F_estatus` DATE NOT NULL,
  `F_cierre` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `id_usuario_alta` VARCHAR(45) NOT NULL,
  `id_usuario_asignado` VARCHAR(45) NOT NULL,
  `id_usuario_ultima_act` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_caso`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tatricaso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tatricaso` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tatricaso` (
  `id_empresa` INT NOT NULL,
  `Tipo_caso` VARCHAR(45) NOT NULL,
  `Num_atributo` INT NOT NULL,
  `Descripcion` VARCHAR(150) NOT NULL,
  `Tipo_dato` VARCHAR(45) NOT NULL,
  `Catalogo` VARCHAR(45) NOT NULL,
  `Default` VARCHAR(45) NULL,
  `Longitud_min` VARCHAR(45) NULL,
  `Longitud_max` VARCHAR(45) NULL,
  `Editable` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empresa`, `Tipo_caso`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tablas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tablas` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tablas` (
  `id_tabla` INT NOT NULL  AUTO_INCREMENT,
  `Descipcion` VARCHAR(150) NOT NULL,
  `id_tabl_dep` INT NULL,
  PRIMARY KEY (`id_tabla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_ntablas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_ntablas` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_ntablas` (
  `id_tabla` INT NOT NULL,
  `id_codigo` VARCHAR(45) NOT NULL,
  `Descipcion` VARCHAR(150) NOT NULL,
  `Campo_A` VARCHAR(45) NULL,
  `Campo_B` VARCHAR(45) NULL,
  `Campo_C` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tabla`, `id_codigo`),
  CONSTRAINT `fk_ntqblas`
    FOREIGN KEY (`id_tabla`)
    REFERENCES `Alesi_BD`.`Alesi_tablas` (`id_tabla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS Alesi_userWeb;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Alesi_userWeb' IDENTIFIED BY 'eGWZXN$gwpDg';

GRANT ALL ON `Alesi_BD`.* TO 'Alesi_userWeb';
GRANT SELECT, INSERT, TRIGGER ON TABLE `Alesi_BD`.* TO 'Alesi_userWeb';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tvalcaso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tvalcaso` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tvalcaso` (
  `id_caso` INT NOT NULL,
  `Num_atributo` INT NOT NULL,
  `Valor` VARCHAR(36000) NULL,
  PRIMARY KEY (`id_caso`),
  CONSTRAINT `fk_2`
    FOREIGN KEY (`id_caso`)
    REFERENCES `Alesi_BD`.`Alesi_tcaso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Alesi_BD`.`Alesi_tvalcaso_2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alesi_BD`.`Alesi_tvalcaso_2` ;

CREATE TABLE IF NOT EXISTS `Alesi_BD`.`Alesi_tvalcaso_2` (
  `Valor1` VARCHAR(36000) NULL,
  `Valor2` VARCHAR(36000) NULL,
  `Valor3` VARCHAR(36000) NULL,
  `Valor4` VARCHAR(36000) NULL,
  `Valor5` VARCHAR(36000) NULL,
  `Valor6` VARCHAR(36000) NULL,
  `Valor7` VARCHAR(36000) NULL,
  `Valor8` VARCHAR(36000) NULL,
  `Valor9` VARCHAR(36000) NULL,
  `Valor10` VARCHAR(36000) NULL,
  `Valor11` VARCHAR(36000) NULL,
  `Valor12` VARCHAR(36000) NULL,
  `Valor13` VARCHAR(36000) NULL,
  `Valor14` VARCHAR(36000) NULL,
  `Valor15` VARCHAR(36000) NULL,
  `Valor16` VARCHAR(36000) NULL,
  `Valor17` VARCHAR(36000) NULL,
  `Valor18` VARCHAR(36000) NULL,
  `Valor19` VARCHAR(36000) NULL,
  `Valor20` VARCHAR(36000) NULL,
  `Valor21` VARCHAR(36000) NULL,
  `Valor22` VARCHAR(36000) NULL,
  `Valor23` VARCHAR(36000) NULL,
  `Valor24` VARCHAR(36000) NULL,
  `Valor25` VARCHAR(36000) NULL,
  `Valor26` VARCHAR(36000) NULL,
  `Valor27` VARCHAR(36000) NULL,
  `Valor28` VARCHAR(36000) NULL,
  `Valor29` VARCHAR(36000) NULL,
  `Valor30` VARCHAR(36000) NULL,
  `Valor31` VARCHAR(36000) NULL,
  `Valor32` VARCHAR(36000) NULL,
  `Valor33` VARCHAR(36000) NULL,
  `Valor34` VARCHAR(36000) NULL,
  `Valor35` VARCHAR(36000) NULL,
  `Valor36` VARCHAR(36000) NULL,
  `Valor37` VARCHAR(36000) NULL,
  `Valor38` VARCHAR(36000) NULL,
  `Valor39` VARCHAR(36000) NULL,
  `Valor40` VARCHAR(36000) NULL,
  `Valor41` VARCHAR(36000) NULL,
  `Valor42` VARCHAR(36000) NULL,
  `Valor43` VARCHAR(36000) NULL,
  `Valor44` VARCHAR(36000) NULL,
  `Valor45` VARCHAR(36000) NULL,
  `Valor46` VARCHAR(36000) NULL,
  `Valor47` VARCHAR(36000) NULL,
  `Valor48` VARCHAR(36000) NULL,
  `Valor49` VARCHAR(36000) NULL,
  `Valor50` VARCHAR(36000) NULL,
  `Valor51` VARCHAR(36000) NULL,
  `Valor52` VARCHAR(36000) NULL,
  `Valor53` VARCHAR(36000) NULL,
  `Valor54` VARCHAR(36000) NULL,
  `Valor55` VARCHAR(36000) NULL,
  `Valor56` VARCHAR(36000) NULL,
  `Valor57` VARCHAR(36000) NULL,
  `Valor58` VARCHAR(36000) NULL,
  `Valor59` VARCHAR(36000) NULL,
  `Valor60` VARCHAR(36000) NULL,
  `Valor61` VARCHAR(36000) NULL,
  `Valor62` VARCHAR(36000) NULL,
  `Valor63` VARCHAR(36000) NULL,
  `Valor64` VARCHAR(36000) NULL,
  `Valor65` VARCHAR(36000) NULL,
  `Valor66` VARCHAR(36000) NULL,
  `Valor67` VARCHAR(36000) NULL,
  `Valor68` VARCHAR(36000) NULL,
  `Valor69` VARCHAR(36000) NULL,
  `Valor70` VARCHAR(36000) NULL,
  `Valor71` VARCHAR(36000) NULL,
  `Valor72` VARCHAR(36000) NULL,
  `Valor73` VARCHAR(36000) NULL,
  `Valor74` VARCHAR(36000) NULL,
  `Valor75` VARCHAR(36000) NULL,
  `Valor76` VARCHAR(36000) NULL,
  `Valor77` VARCHAR(36000) NULL,
  `Valor78` VARCHAR(36000) NULL,
  `Valor79` VARCHAR(36000) NULL,
  `Valor80` VARCHAR(36000) NULL,
  `Valor81` VARCHAR(36000) NULL,
  `Valor82` VARCHAR(36000) NULL,
  `Valor83` VARCHAR(36000) NULL,
  `Valor84` VARCHAR(36000) NULL,
  `Valor85` VARCHAR(36000) NULL,
  `Valor86` VARCHAR(36000) NULL,
  `Valor87` VARCHAR(36000) NULL,
  `Valor88` VARCHAR(36000) NULL,
  `Valor89` VARCHAR(36000) NULL,
  `Valor90` VARCHAR(36000) NULL,
  `Valor91` VARCHAR(36000) NULL,
  `Valor92` VARCHAR(36000) NULL,
  `Valor93` VARCHAR(36000) NULL,
  `Valor94` VARCHAR(36000) NULL,
  `Valor95` VARCHAR(36000) NULL,
  `Valor96` VARCHAR(36000) NULL,
  `Valor97` VARCHAR(36000) NULL,
  `Valor98` VARCHAR(36000) NULL,
  `Valor99` VARCHAR(36000) NULL,
  `Valor100` VARCHAR(36000) NULL)
ENGINE = InnoDB;


INSERT INTO `alesi_tablas` (`id_tabla`, `Descipcion`, `id_tabl_dep`) VALUES
(1, 'Catalogo de Empresas', NULL),
(2, 'Catalogo de Roles', NULL);

INSERT INTO `alesi_ntablas` (`id_tabla`, `id_codigo`, `Descipcion`, `Campo_A`, `Campo_B`, `Campo_C`) VALUES
(1, 'SoporteAlesi', 'Empresa que brinda soporte para Alesi', NULL, NULL, NULL),
(2, 'Dev1', 'Perfil Desarrollador tipo1', NULL, NULL, NULL);


INSERT INTO `alesi_tpersonas` (`id_persona`, `Nombre`, `ApellidoP`, `ApellidoM`, `Edad`, `Sexo`, `Telefono`, `Email`, `id_Empresa`, `Cargo`, `Otros`) VALUES
(1, 'Jesus', 'Acosta', 'Maya', 99, 'M', '9999999999', 'algo@algo', 'SoporteAlesi', 'Developer1', NULL);


INSERT INTO `alesi_tusuarios` (`Usuario`, `id_persona`, `Pass`, `Rol`, `Status`, `F_alta`, `F_ultima_conexion`) VALUES
('JECHUS', 1, 'abc12345', 'Dev1', 'Activo', '2019-10-30', '2019-10-30');

commit;
