/*
-- Query: select * from alesi_tvalcaso
LIMIT 0, 1000

-- Date: 2019-11-09 02:14
*/
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,1,'JOSE PERES LEON');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,2,'PRESIDENTE');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,3,'1-211-2019-1111');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,4,'2019-10-01');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,5,'2019-10-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,6,'1-211-99999');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,7,'0');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,8,'2019-01-01');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,9,'2019-01-01');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,10,'AMPLIA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,11,'NOE SANTIAGO GARCIA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,12,'MARIA LA DEL BARRIO');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,13,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,14,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,15,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,16,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,17,'BMW');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,18,'EL MAS CHINGON');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,19,'2020');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,20,'NEGO');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,21,'56789');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,22,'3456789');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,23,'NFS-1TB');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,24,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,25,'2000000');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,26,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,27,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,28,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,29,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,30,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,31,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,32,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,33,'P');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,34,'ME PEGARON');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,35,'SIN ENTREVISTAS');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,36,'LA FODA DE ALTAVISTA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,37,'ALTAVISTA NUMERO __');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,38,'AQUI VALIO CHICHARO');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,39,'SEPA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,40,'2019-11-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,41,'SAGN9212');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,42,'INNE');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,43,'SEPA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,44,'SEPA DOS');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,45,'11111111111');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,46,'1');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,47,'2019-11-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,48,'LA TORTERIA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,49,'Parece que pese a existir una diferencia de 1 a├â┬▒o exacto entre la versi├â┬│n del Red Dead Redemption II para consolas y PC, Rockstar no ha tenido tiempo para ofrecer un juego perfecto, y es que los usuarios est├â┬ín reportando problemas con los mods.\r\n\r\nRead more https://elchapuzasinformatico.com/');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,50,'SEPA 3');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,51,'SEPA 4');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,52,'LOS CHISMOSOS DE LA CUADRA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,53,'ALGUIEN');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,54,'SEPA 5');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,55,'Si a principios de 2020 ya esper├â┬íbamos los Intel Comet Lake-S de 10 n├â┬║cleos y 20 hilos @ 14nm para el mercado de sobremesa, parece que tendremos que ir apuntando la llegada de una nueva generaci├â┬│n de CPUs AMD Ryzen para eclipsar a la nueva.\r\n\r\nRead more https://elchapuzasinformatico.com/');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,56,'1-211-7898');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,57,'AMPLIA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,58,'2019-11-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,59,'2019-11-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,60,'Junto al Mi Note 10, Xiaomi anunci├â┬│ sus dos nuevos televisores, los Mi TV 5 y Mi TV 5 Pro, los cuales se dividen en tres tama├â┬▒os de 55, 65 y 75 pulgadas. En t├â┬®rminos de panel, la variante Pro ofrece una mayor calidad, adem├â┬ís de contar con una...\r\n\r\nRead more https://elchapuzasinformatico.com/');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,61,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,62,'IXTAPALAPA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,63,'1293/1231:DASD');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,64,'2019-11-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,65,'06:50PM');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,66,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,67,'SEPA');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,68,'El director financiero de Intel, George Davis, en una entrevista con Barron, un peri├â┬│dico semanal estadounidense centrado en la informaci├â┬│n financiera del pa├â┬¡s, coment├â┬│ la salud financiera de la empresa, y algunas de las razones que subyacen a...\r\n\r\nRead more https://elchapuzasinformatico.com/');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,69,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,70,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,71,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,72,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,73,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (1,74,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,1,'Gustavo Pineda González.');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,2,'Analista de Valuación y Dictamen.');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,3,'1-211-2019-M-123');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,4,'2019-01-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,5,'2019-01-06');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,6,'1902977');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,7,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,8,'2019-01-03');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,9,'2020-01-03');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,10,'A');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,11,'Lucia Duran González');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,12,'');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,13,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,14,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,15,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,16,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,17,'0004');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,18,'00040010');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,19,'2014');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,20,'1');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,21,'JTFSX23P6148447');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,22,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,23,'F39 AYF');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,24,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,25,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,26,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,27,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,28,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,29,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,30,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,31,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,32,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,33,'R');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,34,'El Ing Christian recoge camioneta en tula hdgo el dia jueves 3 para probable trabajo y verificacion vehicular el dia sabado 05/01 me llama por la tarde informandome que ya no se encontraba camioneta donde la habia dejado estacionada ');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,35,'Es importante mencionar que derivado de la condición del presente siniestro, se opta llevar una investigación de manera cronológica, supeditada a que se cumplan los tiempos de cada una de las fases de la presente investigación, agotando cada fase  con los tiempos establecidos en el plan de trabajo.\n\n1.- Con fecha 10 de enero del presente año, se hace un análisis detallado del expediente, con la finalidad de obtener datos que nos permitan determinar el procedimiento a seguir en la presente investigación.\n\n2.- Con fecha 15 de enero del presente año, se acude al lugar señalado en la declaración de siniestro, apoyando la búsqueda de datos de prueba para acreditar la preexistencia del vehículo asegurado, conforme a lo narrado por la C. Lucia Duran Gonzalez al momento de reportar el siniestro.  Es importante señalar que el ultimo conductor del vehículo fue el C. Christian Martin Mercado López.\n\n3.- Con fecha 14 de Enero del año en curso, se sostuvo entrevista en las instalaciones de SURA con la C. Lucia Duran González, únicamente argumentando que el C. Christian Martin Mercado Lopez,  se encontraba realizando trabajos propios de su empresa Ciudad Juárez, por tal motivo no podía asistir a la cita en cuanto el regresara podríamos tener una entrevista con el C. Christian Martin Mercado López , que lo único que ella sabía era lo que había declarado cuando reporto el siniestro, al tiempo que pudimos notar no contaba de momento con la documentación en orden de su vehículo robado y su carpeta de investigación aun estaba incompleta recomendándole ordenar su documentación así como tener entrevista con su empleado.\n\n4.- En fecha 21 de enero del año en curso en las instalaciones de SURA nos entrevistamos con el C. Christian Martín Mercado López, quien refiere que el día jueves 03 de enero del año en curso acude a la Ciudad de Tula Hidalgo por la camioneta de referencia a efecto de trasladarla a la Ciudad de México, ya que tenía pendiente un trabajo y verificación vehicular de la misma, así mismo refiere ser él quien lleva a cabo los tramites de diversos vehículos que tiene la C. Lucia Duran Gonzalez. Nos da referencia que dejo estacionada la camioneta en el exterior de la oficina entre los números 312 y 315 de la mencionada calle y según su dicho la camioneta ahí se queda estacionada, y es hasta el sábado 05 que se percata ya no está en el lugar donde la dejo, a preguntas expresas de ¿Si había movido o prestado la camioneta? R.  Refiere nunca la mueve de lugar, ¿Dónde verificaría la unidad asegurada? R.  Refiere la llevaría a la Avenida Central en el Estado de México.\n\nEs importante precisar que el sujeto en todo momento se torna nervioso y evasivo a cuestionamientos dejando claro miente en su dicho.\n\n5.- En fecha 08 de febrero del año en curso, se tuvo entrevista en las instalaciones de SURA, con la C. Lucia Duran, quien a la fecha no ha podido acreditar la preexistencia del vehículo, toda vez que como se desprende de las diligencias documentales y de campo el vehículo tuvo que haber sido verificada en segundo periodo de verificación vehicular correspondiente al año 2018. Por tanto, se comprometió a conseguir la documentación que acredite su dicho.\n');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,36,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,37,'Calle Oriente 178 entre los numeros 312 y 315Colonia  Alcaldia Venustiano Carranza');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,38,'Se observa en lugar del robo una Colonia que en su mayoría existen casas habitación, en la esquina norte junto al número 312 se estableció una Tienda de Abarrotes. En la esquina sur, se encuentra instalado un Taller de Hojalatería, ya que hacen trabajos en la calle.\nAl preguntar a los vecinos si sabian del robo nos argumentan no tener conocimiento de los hechos que se investigan. Sin embargo, nos dan referencias del C. Christian Martin Mercado López, como una persona bastante conflictiva por estorbar con los vehículos que lleva y estacionarse frente a las entradas de las casas. Así mismo se nos refiere que la unidad asegurada en ningún momento estuvo estacionada días antes de que fuera robada.\n');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,39,'Factura');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,40,'2018-06-27');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,41,'Pick Uplandia S.A de C.V');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,42,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,43,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,44,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,45,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,46,'3');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,47,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,48,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,49,'No se realiza, cotejo alguno, derivado a que conforme se realizaba la verificación se presentaban diversas anomalías que le fueron notificadas a la C. Lucia Duran González, por lo anterior y al no subsanar dichas anomalías aunado a que se logró hacer la recuperación del vehículo asegurado, no fue posible verificar la autenticidad de dicha documental.');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,50,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,51,'Oriente 138, estacionada frente a los números 312 y 315, Col. Moctezuma 2ª Secc. Alcaldía Venustiano Carranza, Ciudad de México.');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,52,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,53,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,54,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,55,'A pesar de solicitar en diversas ocasiones a la C. Lucia Duran González, se nos presentara documentales para acreditar la preexistencia del vehículo, esto no fue posible ya que los documentos que nos presentaba para tratar de acreditar la preexistencia de la unidad asegurada, apuntalaban una línea más de investigación. Es importante mencionar que los vecinos del lugar donde supuestamente ocurre el robo, en ningún momento vieron la unidad asegurada estacionada. Externan sus quejas, ya que el C. Christian Martín Mercado López estaciona diversos vehículos en las entradas a los domicilios contiguos, sin embargo, aseguran no recordar una camioneta estacionada por varios días, con las características del bien asegurado.');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,56,'N');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,57,'N/A');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,58,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,59,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,60,'Se nos hace saber por parte de la C. Lucia Duran González, que no se encontraba asegurada anteriormente por ser un vehículo de reciente adquisición');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,61,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,62,'3');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,63,'CI-FVC/VC-2/UI-1 S/D/00005/01-2019');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,64,'2019-01-05');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,65,'23:10');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,66,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,67,NULL);
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,68,'Se encuentra debidamente registrada la Carpeta de Investigación en las diversas plataformas de Seguridad Publica.');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,69,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,70,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,71,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,72,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,73,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,74,'S');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,75,'R');
INSERT INTO `alesi_tvalcaso` (`ID_CASO`,`NUM_ATRIBUTO`,`VALOR`) VALUES (2,76,'Con fecha 10 de enero del presente año, se turna a esta firma la investigación de referencia por la posibilidad de encontrarnos ante una falsedad en la declaración y un posible robo preexistente al inicio de vigencia.\n\nEn la misma fecha nos damos a la tarea inmediata de comenzar con la presente investigación, inicialmente con la solicitud de los audios de cabina y realizando las gestiones propias para enriquecer la presente investigación.\n\nUn segundo elemento que se considera para declinar el presente siniestro se basa en las diversas documentales para acreditar la preexistencia del vehículo, apuntalaban una línea más de investigación y que arrojaba como resultado el robo previo al inicio de vigencia. Es importante mencionar que los vecinos del lugar donde supuestamente ocurre el robo, en ningún momento vieron la unidad asegurada estacionada por varios días.\n\nUn tercer elemento que apuntala la información del presente informe consiste en la entrevista con los CC Christian Martín Mercado López y Lucia Duran González,, encontrado discrepancias conforme a los datos de prueba recolectados en el lugar del siniestro, y a los manifestados en las entrevistas por parte del C. Christian Martín Mercado López. Adicionalmente la información proporcionada la consideramos falaz, ya que se encontraba alejada de toda lógica y de la mecánica real del siniestro. \n\nAnte la situación anterior y derivado de que se le hace saber a la C. Lucia Duran González,, la falsedad de la declaración inicial por parte del C. Christian Martín Mercado López, manifiesta que no es su deseo intervenir en ningún procedimiento legal, por lo que firma el desistimiento correspondiente.\n\nPor lo anterior, bajo el orden de argumentos y datos de prueba señalados, una vez que dicha información se contrasta con entrevistas, resulta improcedente el siniestro, toda vez que se puede comprobar de manera indubitable que la mecánica de hechos narrada al ajustador, no corresponde. Existiendo dolo en la declaración inicial al ajustador, simulando los hechos, encontrando para ello diversos datos de prueba e indicios que fueron susceptibles de investigación.\n\nSin más por el momento reciba un afectuoso saludo, no sin antes reiterarle que quedo a sus órdenes para cualquier aclaración al respecto.\n');
